import jsPDF from 'jspdf';
import QRCode from 'qrcode';

interface Vitals {
  bp: string;
  pr: string;
  spo2: string;
  temp: string;
  height: string;
  weight: string;
  bmi: string;
  age: string;
  gender: string;
}

interface Diagnosis {
  name: string;
  confidence?: string;
  description?: string;
}

interface Medicine {
  name: string;
  type: string;
  dose: string;
  route: string;
  frequency: string;
  duration: string;
  instructions: string;
}

interface DiagnosticTest {
  testName: string;
  testType?: string;
  reason?: string;
}

interface PatientInfo {
  name: string;
  phone: string;
  email: string;
  address: string;
  medicalHistory: string;
}

interface DoctorProfile {
  name: string;
  qualifications: string;
  specialization: string;
  registrationNo: string;
  clinicName: string;
  clinicAddress: string;
  clinicCity: string;
  clinicState: string;
  clinicPincode: string;
  phone: string;
  email: string;
  website: string;
  chamberName: string;
  chamberAddress: string;
  chamberTimings: string;
  chamberPhone: string;
  signatureImage: string;
  headerImage: string;
  footerImage: string;
  logoImage: string;
}

interface PrescriptionData {
  patientInfo: PatientInfo;
  vitals: Vitals;
  symptoms: string[];
  clinicalFindings: string;
  diagnoses: Diagnosis[];
  diagnosisType: string;
  tests: DiagnosticTest[];
  medicines: Medicine[];
  doctorProfile?: DoctorProfile;
}

// Generate a simple barcode pattern
function generateBarcode(doc: jsPDF, code: string, x: number, y: number, width: number, height: number) {
  const barWidth = width / (code.length * 2 + 10);
  let currentX = x;
  
  // Start pattern
  doc.setFillColor(0, 0, 0);
  doc.rect(currentX, y, barWidth, height, 'F');
  currentX += barWidth * 2;
  doc.rect(currentX, y, barWidth, height, 'F');
  currentX += barWidth * 2;
  
  // Data pattern
  for (let i = 0; i < code.length; i++) {
    const charCode = code.charCodeAt(i);
    if (charCode % 2 === 0) {
      doc.rect(currentX, y, barWidth, height, 'F');
    }
    currentX += barWidth;
    if (charCode % 3 === 0) {
      doc.rect(currentX, y, barWidth * 0.5, height, 'F');
    }
    currentX += barWidth;
  }
  
  // End pattern
  doc.rect(currentX, y, barWidth, height, 'F');
  currentX += barWidth * 2;
  doc.rect(currentX, y, barWidth, height, 'F');
  
  // Barcode text
  doc.setFontSize(6);
  doc.setTextColor(0, 0, 0);
  doc.text(code, x + width / 2, y + height + 3, { align: 'center' });
}

// Generate unique prescription ID
function generatePrescriptionId(): string {
  const date = new Date();
  const dateStr = date.toISOString().slice(0, 10).replace(/-/g, '');
  const randomStr = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `RX${dateStr}${randomStr}`;
}

export async function generatePrescriptionPdf(data: PrescriptionData): Promise<void> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const headerHeight = 45;
  const footerHeight = 25;
  const contentTop = headerHeight + 5;
  const contentBottom = pageHeight - footerHeight - 10;
  let y = contentTop;
  
  const prescriptionId = generatePrescriptionId();
  const prescriptionDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Generate QR Code
  let qrCodeDataUrl = '';
  const fullAddress = data.doctorProfile ? 
    `${data.doctorProfile.clinicName}\n${data.doctorProfile.clinicAddress}\n${data.doctorProfile.clinicCity}, ${data.doctorProfile.clinicState} ${data.doctorProfile.clinicPincode}\nPhone: ${data.doctorProfile.phone}` 
    : 'Prescription generated by AI Prescription Builder';
  
  try {
    qrCodeDataUrl = await QRCode.toDataURL(fullAddress, { width: 200, margin: 1 });
  } catch (e) {
    console.error('QR Code generation failed:', e);
  }

  // Helper functions
  const addHeader = (pageNum: number, totalPages: number) => {
    if (data.doctorProfile?.headerImage) {
      try {
        doc.addImage(data.doctorProfile.headerImage, 'PNG', 0, 0, pageWidth, headerHeight);
      } catch {
        drawDefaultHeader(pageNum, totalPages);
      }
    } else {
      drawDefaultHeader(pageNum, totalPages);
    }
  };

  const drawDefaultHeader = (pageNum: number, totalPages: number) => {
    // Header background
    doc.setFillColor(15, 82, 186);
    doc.rect(0, 0, pageWidth, headerHeight, 'F');
    
    // Accent line
    doc.setFillColor(59, 130, 246);
    doc.rect(0, headerHeight - 3, pageWidth, 3, 'F');

    // Logo area (if available)
    if (data.doctorProfile?.logoImage) {
      try {
        doc.addImage(data.doctorProfile.logoImage, 'PNG', margin, 5, 25, 25);
      } catch {}
    }

    const textStartX = data.doctorProfile?.logoImage ? margin + 30 : margin;

    // Doctor name and qualifications
    if (data.doctorProfile?.name) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text(data.doctorProfile.name, textStartX, 12);
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(data.doctorProfile.qualifications || '', textStartX, 18);
      
      if (data.doctorProfile.specialization) {
        doc.setFontSize(8);
        doc.text(data.doctorProfile.specialization, textStartX, 23);
      }
      
      doc.setFontSize(8);
      doc.text(`Reg. No: ${data.doctorProfile.registrationNo || 'N/A'}`, textStartX, 28);
    }

    // Clinic info on right
    if (data.doctorProfile?.clinicName) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(data.doctorProfile.clinicName, pageWidth - margin, 10, { align: 'right' });
      
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      
      let rightY = 15;
      if (data.doctorProfile.clinicAddress) {
        const addressLines = doc.splitTextToSize(data.doctorProfile.clinicAddress, 60);
        addressLines.forEach((line: string) => {
          doc.text(line, pageWidth - margin, rightY, { align: 'right' });
          rightY += 4;
        });
      }
      
      const cityState = [data.doctorProfile.clinicCity, data.doctorProfile.clinicState, data.doctorProfile.clinicPincode]
        .filter(Boolean).join(', ');
      if (cityState) {
        doc.text(cityState, pageWidth - margin, rightY, { align: 'right' });
        rightY += 4;
      }
      
      if (data.doctorProfile.phone) {
        doc.text(`Ph: ${data.doctorProfile.phone}`, pageWidth - margin, rightY, { align: 'right' });
        rightY += 4;
      }
      
      if (data.doctorProfile.email) {
        doc.text(data.doctorProfile.email, pageWidth - margin, rightY, { align: 'right' });
      }
    }

    // Page number
    doc.setFontSize(7);
    doc.setTextColor(200, 200, 200);
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, headerHeight - 5, { align: 'center' });
  };

  const addFooter = () => {
    const footerY = pageHeight - footerHeight;
    
    if (data.doctorProfile?.footerImage) {
      try {
        doc.addImage(data.doctorProfile.footerImage, 'PNG', 0, footerY, pageWidth, footerHeight);
        return;
      } catch {}
    }

    // Default footer
    doc.setFillColor(248, 250, 252);
    doc.rect(0, footerY, pageWidth, footerHeight, 'F');
    
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, footerY + 2, pageWidth - margin, footerY + 2);

    // Barcode
    generateBarcode(doc, prescriptionId, margin, footerY + 5, 50, 10);

    // QR Code
    if (qrCodeDataUrl) {
      try {
        doc.addImage(qrCodeDataUrl, 'PNG', pageWidth - margin - 20, footerY + 4, 18, 18);
      } catch {}
    }

    // Footer text
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text('This is a computer generated prescription.', pageWidth / 2, footerY + 10, { align: 'center' });
    doc.text('Please consult your healthcare provider for any questions.', pageWidth / 2, footerY + 14, { align: 'center' });
    
    // Chamber info in footer (if available)
    if (data.doctorProfile?.chamberName && data.doctorProfile?.chamberTimings) {
      doc.setFontSize(6);
      doc.text(`Chamber: ${data.doctorProfile.chamberName} | ${data.doctorProfile.chamberTimings}`, pageWidth / 2, footerY + 18, { align: 'center' });
    }
    
    doc.setFontSize(6);
    doc.text(`ID: ${prescriptionId}`, pageWidth / 2, footerY + 22, { align: 'center' });
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > contentBottom) {
      addFooter();
      doc.addPage();
      y = contentTop;
      return true;
    }
    return false;
  };

  const addSectionHeader = (text: string) => {
    checkPageBreak(15);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y - 4, pageWidth - margin * 2, 10, 2, 2, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text(text, margin + 5, y + 2);
    y += 12;
  };

  const addText = (text: string, indent = 0) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2 - indent);
    lines.forEach((line: string) => {
      checkPageBreak(5);
      doc.text(line, margin + indent, y);
      y += 5;
    });
  };

  // Count total pages (approximate)
  let totalPages = 1;
  
  // First pass - just add header placeholder
  addHeader(1, totalPages);
  
  // Prescription info bar
  doc.setFillColor(239, 246, 255);
  doc.rect(margin, y, pageWidth - margin * 2, 12, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 64, 175);
  doc.text(`Date: ${prescriptionDate}`, margin + 5, y + 7);
  doc.text(`Prescription ID: ${prescriptionId}`, pageWidth - margin - 5, y + 7, { align: 'right' });
  y += 18;

  // Patient Information
  if (data.patientInfo.name) {
    addSectionHeader('PATIENT INFORMATION');
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(`Name: ${data.patientInfo.name}`, margin + 5, y);
    
    if (data.vitals.age || data.vitals.gender) {
      const ageGender = [data.vitals.age ? `${data.vitals.age} yrs` : '', data.vitals.gender].filter(Boolean).join(' / ');
      doc.text(ageGender, pageWidth - margin - 5, y, { align: 'right' });
    }
    y += 6;
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    
    if (data.patientInfo.phone) {
      doc.text(`Phone: ${data.patientInfo.phone}`, margin + 5, y);
      y += 5;
    }
    if (data.patientInfo.address) {
      doc.text(`Address: ${data.patientInfo.address}`, margin + 5, y);
      y += 5;
    }
    y += 5;
  }

  // Vitals (compact)
  if (data.vitals.bp || data.vitals.pr || data.vitals.temp) {
    addSectionHeader('VITAL SIGNS');
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    
    const vitalsRow1 = [];
    if (data.vitals.bp) vitalsRow1.push(`BP: ${data.vitals.bp}`);
    if (data.vitals.pr) vitalsRow1.push(`Pulse: ${data.vitals.pr} bpm`);
    if (data.vitals.spo2) vitalsRow1.push(`SpO2: ${data.vitals.spo2}%`);
    if (data.vitals.temp) vitalsRow1.push(`Temp: ${data.vitals.temp}°F`);
    
    const vitalsRow2 = [];
    if (data.vitals.height) vitalsRow2.push(`Height: ${data.vitals.height} cm`);
    if (data.vitals.weight) vitalsRow2.push(`Weight: ${data.vitals.weight} kg`);
    if (data.vitals.bmi) vitalsRow2.push(`BMI: ${data.vitals.bmi}`);
    
    if (vitalsRow1.length) {
      doc.text(vitalsRow1.join('   |   '), margin + 5, y);
      y += 6;
    }
    if (vitalsRow2.length) {
      doc.text(vitalsRow2.join('   |   '), margin + 5, y);
      y += 6;
    }
    y += 3;
  }

  // Symptoms
  if (data.symptoms.length > 0) {
    addSectionHeader('PRESENTING COMPLAINTS');
    data.symptoms.forEach((symptom) => {
      checkPageBreak(6);
      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      doc.text(`• ${symptom}`, margin + 8, y);
      y += 5;
    });
    y += 5;
  }

  // Clinical Findings
  if (data.clinicalFindings) {
    addSectionHeader('CLINICAL FINDINGS');
    addText(data.clinicalFindings, 5);
    y += 5;
  }

  // Diagnosis
  if (data.diagnoses.length > 0) {
    addSectionHeader(`DIAGNOSIS (${data.diagnosisType.toUpperCase()})`);
    data.diagnoses.forEach((diagnosis, index) => {
      checkPageBreak(15);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(`${index + 1}. ${diagnosis.name}`, margin + 5, y);
      y += 5;
      
      if (diagnosis.description) {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 116, 139);
        const descLines = doc.splitTextToSize(diagnosis.description, pageWidth - margin * 2 - 15);
        descLines.forEach((line: string) => {
          doc.text(line, margin + 10, y);
          y += 4;
        });
      }
      y += 3;
    });
    y += 3;
  }

  // Tests
  if (data.tests.length > 0) {
    addSectionHeader('INVESTIGATIONS ADVISED');
    data.tests.forEach((test, index) => {
      checkPageBreak(10);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(51, 65, 85);
      doc.text(`${index + 1}. ${test.testName}${test.testType ? ` (${test.testType})` : ''}`, margin + 5, y);
      y += 5;
      
      if (test.reason) {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 116, 139);
        doc.text(`Reason: ${test.reason}`, margin + 10, y);
        y += 5;
      }
    });
    y += 5;
  }

  // Medicines with RX symbol
  if (data.medicines.length > 0 && data.medicines.some(m => m.name)) {
    checkPageBreak(20);
    
    // RX Symbol
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('℞', margin, y + 5);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('PRESCRIBED MEDICATIONS', margin + 15, y);
    y += 12;
    
    const filteredMedicines = data.medicines.filter(m => m.name);
    
    filteredMedicines.forEach((medicine, index) => {
      checkPageBreak(30);
      
      // Medicine box
      doc.setFillColor(255, 251, 235);
      doc.setDrawColor(251, 191, 36);
      doc.roundedRect(margin, y - 3, pageWidth - margin * 2, 24, 2, 2, 'FD');
      
      // Medicine number badge
      doc.setFillColor(251, 191, 36);
      doc.circle(margin + 8, y + 5, 4, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text(`${index + 1}`, margin + 8, y + 6.5, { align: 'center' });
      
      // Medicine name
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(`${medicine.name}`, margin + 15, y + 3);
      
      if (medicine.type) {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 116, 139);
        doc.text(`(${medicine.type})`, margin + 15 + doc.getTextWidth(medicine.name) + 3, y + 3);
      }
      
      // Medicine details in two columns
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      
      const col1X = margin + 15;
      const col2X = pageWidth / 2;
      let detailY = y + 10;
      
      if (medicine.dose) {
        doc.text(`Dose: ${medicine.dose}`, col1X, detailY);
      }
      if (medicine.route) {
        doc.text(`Route: ${medicine.route}`, col2X, detailY);
      }
      detailY += 5;
      
      if (medicine.frequency) {
        doc.text(`Frequency: ${medicine.frequency}`, col1X, detailY);
      }
      if (medicine.duration) {
        doc.text(`Duration: ${medicine.duration}`, col2X, detailY);
      }
      
      if (medicine.instructions) {
        detailY += 5;
        doc.setFont('helvetica', 'italic');
        doc.text(`Instructions: ${medicine.instructions}`, col1X, detailY);
      }
      
      y += 30;
    });
    y += 5;
  }

  // Medical History (if provided)
  if (data.patientInfo.medicalHistory) {
    addSectionHeader('MEDICAL HISTORY');
    addText(data.patientInfo.medicalHistory, 5);
    y += 5;
  }

  // Signature
  if (data.doctorProfile?.signatureImage || data.doctorProfile?.name) {
    checkPageBreak(35);
    y += 10;
    
    const signX = pageWidth - margin - 50;
    
    if (data.doctorProfile?.signatureImage) {
      try {
        doc.addImage(data.doctorProfile.signatureImage, 'PNG', signX, y, 45, 18);
        y += 20;
      } catch {
        doc.setDrawColor(100, 116, 139);
        doc.line(signX, y + 15, signX + 45, y + 15);
        y += 18;
      }
    } else {
      doc.setDrawColor(100, 116, 139);
      doc.line(signX, y + 15, signX + 45, y + 15);
      y += 18;
    }
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(data.doctorProfile?.name || 'Doctor\'s Signature', signX + 22.5, y, { align: 'center' });
    
    if (data.doctorProfile?.qualifications) {
      y += 4;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      doc.text(data.doctorProfile.qualifications, signX + 22.5, y, { align: 'center' });
    }
  }

  // Add footer to current page
  addFooter();

  // Add headers and footers to all pages
  totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    // Redraw header with correct page numbers
    if (!data.doctorProfile?.headerImage) {
      // Only redraw if using default header
      addHeader(i, totalPages);
    }
  }

  // Save the PDF
  const patientName = data.patientInfo.name ? data.patientInfo.name.replace(/\s+/g, '_') : 'patient';
  const fileName = `Prescription_${patientName}_${prescriptionId}.pdf`;
  doc.save(fileName);
}
